"""Add news_link field to UserContent

Revision ID: 0724832d5ffd
Revises: 
Create Date: 2025-06-12 15:30:58.053188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0724832d5ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user_content')]
    
    if 'news_link' not in columns:
        with op.batch_alter_table('user_content', schema=None) as batch_op:
            batch_op.add_column(sa.Column('news_link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_content', schema=None) as batch_op:
        batch_op.drop_column('news_link')

    # ### end Alembic commands ###
