"""Recreate missing migration

Revision ID: dcc5a05d2b56
Revises: 0724832d5ffd
Create Date: 2025-06-16 08:29:24.299752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc5a05d2b56'
down_revision = '0724832d5ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns already exist before adding them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('user_content')]
    
    with op.batch_alter_table('user_content', schema=None) as batch_op:
        if 'is_in_seattle' not in columns:
            batch_op.add_column(sa.Column('is_in_seattle', sa.Boolean(), nullable=True))
        # batch_op.add_column(sa.Column('news_link', sa.Text(), nullable=True))
        # batch_op.add_column(sa.Column('seeded_likes_count', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('seeded_comments_count', sa.Integer(), nullable=True))
        # batch_op.alter_column('is_seeded',
        #        existing_type=sa.BOOLEAN(),
        #        nullable=True,
        #        existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_content', schema=None) as batch_op:
        batch_op.alter_column('is_seeded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.drop_column('seeded_comments_count')
        batch_op.drop_column('seeded_likes_count')
        batch_op.drop_column('news_link')
        batch_op.drop_column('is_in_seattle')

    # ### end Alembic commands ###
